# Generated by Django 3.1.4 on 2021-08-17 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epsilon', models.FloatField()),
                ('speed_learning', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('nb_games_training', models.IntegerField()),
                ('nb_games_training_wins', models.IntegerField()),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(db_index=True, max_length=146)),
                ('position', models.CharField(db_index=True, max_length=2)),
                ('position2', models.CharField(db_index=True, max_length=2)),
                ('q_table', models.CharField(max_length=100)),
                ('ai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.ai')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
