# Generated by Django 3.1.4 on 2021-08-17 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '__first__'),
        ('connection', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_State',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_player', models.IntegerField()),
                ('board', models.CharField(max_length=146)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Player',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=146)),
                ('num_player', models.IntegerField()),
                ('old_direction', models.IntegerField(null=True)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game_state')),
                ('previous_state_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AI.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.user')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
