# Generated by Django 3.1.4 on 2021-08-17 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=25)),
                ('color2', models.CharField(max_length=25)),
                ('nb_games', models.IntegerField()),
                ('nb_games_wins', models.IntegerField()),
                ('ai_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AI.ai')),
                ('user_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.user_data')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
